---
- name: create LV
  user: root
  hosts: lvm

  vars_files:
    - /vars/lvcreate_vars.yml

  tasks:

    - name: 'Installing XFS tools if necessary'
      yum: name=xfsprogs state=latest

    - name: 'Installing ext2/3 tools if necessary'
      yum: name=e2fsprogs state=latest

    - name: 'Creating Logical Volume'
      command: lvcreate -L "{{ item.0 }}" -n "{{ item.1 }}" "{{ vgname }}"
      with_together:
        - "{{ lvsize }}"
        - "{{ lvname }}"

    - name: 'Making filesystem'
      command: 'mkfs.{{ item.0 }} /dev/mapper/{{ vgname }}-{{ item.1 }}'
      with_together:
        - "{{ fstype }}"
        - "{{ lvname }}"

    - name: 'Mount the new filesystem and add to /etc/fstab'
      mount: name="{{ item.0 }}" src=/dev/mapper/"{{ vgname }}"-"{{ item.1 }}" fstype="{{ item.2 }}" state=mounted
      with_together:
        - "{{ mountpoint }}"
        - "{{ lvname }}"
        - "{{ fstype }}"
