---
- name: resize LV
  user: root
  hosts: lvm
  vars_files:
    - /vars/lvresize_vars.yml

  tasks:

    - name: 'Resizing Logical Volume'
      command: lvresize -L "{{ item.0 }}" /dev/"{{ item.1 }}"/"{{ item.2 }}"
      with_together:
        - "{{ lvsize }}"
        - "{{ vgname }}"
        - "{{ lvname }}"

    - name: 'Executing resize2fs'
      command: resize2fs /dev/"{{ item.0 }}"/"{{ item.1 }}"
      with_together:
        - "{{ vgname }}"
        - "{{ lvname }}"
